### ISSUE TITLE
In case this can help

### ISSUE THREAD

**Issue by cyrinux** [heywoodlh/gotify-imap-watcher#1]
Hi! 
I just saw you in my feed and think about I did this sometimes ago and it works AFAIK https://github.com/cyrinux/imap2gotify

I would be happy to have contributions for improvement if needed.

Cheers 🙂

**Comment by heywoodlh** [comment]
Hah, your tool is way better than what I was writing. Was mostly just doing this as an exercise. 

But, will likely be using your tool instead! Thanks for the awareness :)
